# Generated by Django 5.0.1 on 2026-01-14 23:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Adjustment')], max_length=10)),
                ('points_change', models.IntegerField()),
                ('balance_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'points_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('aluminum', 'Aluminum'), ('paper', 'Paper')], max_length=20)),
                ('item_code', models.CharField(db_index=True, help_text='Barcode or QR code from item', max_length=100)),
                ('points_earned', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('machine_id', models.CharField(blank=True, help_text='ID of the recycling machine', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recycling_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
