# Generated by Django 5.0.1 on 2026-01-14 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recycling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_records', to='recycling.recyclingtransaction'),
        ),
        migrations.AddIndex(
            model_name='recyclingtransaction',
            index=models.Index(fields=['user', '-created_at'], name='recycling_t_user_id_ec61c6_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclingtransaction',
            index=models.Index(fields=['item_code', 'user'], name='recycling_t_item_co_b30508_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclingtransaction',
            index=models.Index(fields=['status'], name='recycling_t_status_16896e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recyclingtransaction',
            constraint=models.UniqueConstraint(fields=('user', 'item_code'), name='unique_user_item'),
        ),
        migrations.AddIndex(
            model_name='pointshistory',
            index=models.Index(fields=['user', '-created_at'], name='points_hist_user_id_6a69c5_idx'),
        ),
    ]
