# Generated by Django 5.0.1 on 2026-01-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earned'), ('payout', 'Payout')], max_length=10),
        ),
    ]
