# Generated by Django 5.0.1 on 2026-01-15 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_alter_pointshistory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingtransaction',
            name='weight_grams',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in grams from sensor', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
    ]
